/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

void sassert(int X ) 
{ 


  {
  return;
}
}
int main(void) 
{ 
  int b ;
  int a ;

  {
  b = 0;
  a = b - 1;
  {
  while (1) {
    while_continue: /* CIL Label */ ;
    if (b < 8) {

    } else {
      goto while_break;
    }
    b = b + 1;
    if (b == 8) {
      a = 1;
    } else {

    }
  }
  while_break: /* CIL Label */ ;
  }
  {
  sassert(a > 0);
  }
  return (0);
}
}
