/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

void sassert(int X ) 
{ 


  {
  return;
}
}
int main(void) 
{ 
  int x ;
  int y ;
  int z ;

  {
  x = 1;
  y = 2;
  z = 0;
  {
  while (1) {
    while_continue: /* CIL Label */ ;
    if (x < y) {

    } else {
      goto while_break;
    }
    x = x + 1;
  }
  while_break: /* CIL Label */ ;
  }
  {
  sassert(x >= z);
  }
  return (0);
}
}
