/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

void sassert(int X ) 
{ 


  {
  return;
}
}
extern int ( /* missing proto */  assert)() ;
int main(void) 
{ 
  int x ;
  int y ;

  {
  x = 1;
  y = 0;
  if (x > y) {
    {
    x = y - x;
    assert(x > 0);
    }
  } else {

  }
  return (0);
}
}
