/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

void sassert(int X ) 
{ 


  {
  return;
}
}
extern int ( /* missing proto */  assert)() ;
int main(void) 
{ 
  int i ;
  int x ;
  int y ;
  int ctr ;

  {
  x = ctr;
  y = x;
  y = x + 1;
  if (ctr == i) {
    {
    assert(y == i + 1);
    }
  } else {

  }
  return (0);
}
}
